name: finance_tracker
description: "Personal Finance Tracker - Ustoz AI task"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flex_color_scheme: ^8.2.0
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  flutter_bloc: ^9.1.1
  result_dart: ^2.1.1
  get_it: ^8.2.0
  talker: ^5.0.0
  shimmer: ^3.0.0
  google_fonts: ^6.2.1
  go_router: ^15.1.2
  intl: ^0.20.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  intl_utils: ^2.8.10
  build_runner: ^2.7.0


flutter:
  uses-material-design: true


flutter_intl:
  enabled: true
  arb_dir: lib/core/l10n
  output_dir: lib/core/l10n/generated
  class_name: AppLocalizations
  main_locale: en