// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class AppFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPgu6bWMeRIwZx0JT_QpDIFtTRrCTB81s',
    appId: '1:45957131353:android:a302266b36964f48881548',
    messagingSenderId: '45957131353',
    projectId: 'exam-project-7f300',
    databaseURL: 'https://exam-project-7f300-default-rtdb.firebaseio.com',
    storageBucket: 'exam-project-7f300.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDe7x0E-DR2t_m1jhBbPBWSzFakX5r5O2g',
    appId: '1:45957131353:ios:d3ccd7642800890c881548',
    messagingSenderId: '45957131353',
    projectId: 'exam-project-7f300',
    databaseURL: 'https://exam-project-7f300-default-rtdb.firebaseio.com',
    storageBucket: 'exam-project-7f300.firebasestorage.app',
    iosClientId: '45957131353-28iogglak599mhdtk0p779mgm6rslvjc.apps.googleusercontent.com',
    iosBundleId: 'com.sultonbek.financeTracker',
  );
}
